prevent complex but valid bash ENV from causing fatal startup error
This only occurred when running upbanner.debug and a complex ENV variable, PS1

o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalArgumentException: Could not resolve placeholder 'last_stat' in value